# Ansible brew cask stuff has some issues, so just do it myself
---
- hosts: all
  tasks:
  - name: Install brew casks
    register: install_output
    ansible.builtin.shell:
      cmd: |
        {{ ('brew tap ' + item.repo) if item.repo is defined }}
        brew install --cask {{ item.package }}
    changed_when: "'already installed' not in install_output.stderr"
    loop: "{{ brew_cask_packages }}"
