---
- hosts: all
  tasks:
    #   - name: install iterm2 fish shell integration
    #     shell:curl -L https://iterm2.com/shell_integration/fish -o ~/.iterm2_shell_integration.fish
  - name: make fish config directory
    file:
      path: ~/.config/fish/
      state: directory
  - name: read login shell
    command: dscl . -read /Users/{{ lookup('env', 'USER') }} UserShell
    register: login_shell
    changed_when: false
  - name: set fish as login shell
    when: fish_path not in login_shell.stdout
    vars:
      fish_path: /opt/homebrew/bin/fish
    block:
    - name: ask for sudo password
      pause:
        prompt: "sudo password (to set fish as login shell)"
        echo: false
      register: sudo_prompt
      no_log: true
    - name: allow fish as a login shell
      become: true
      vars:
        ansible_become_password: "{{ sudo_prompt.user_input }}"
      lineinfile:
        path: /etc/shells
        line: "{{ fish_path }}"
    - name: set login shell
      become: true
      vars:
        ansible_become_password: "{{ sudo_prompt.user_input }}"
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: "{{ fish_path }}"
