- import_playbook: brew_packages.yml
- import_playbook: fish.yml
- import_playbook: dotfiles.yml
- import_playbook: vim_plug.yml
- import_playbook: tmux.yml
- import_playbook: frontend.yml
- import_playbook: local_bin.yml
- import_playbook: brew_cask.yml
- import_playbook: pyenv.yml
